SET NAMES utf8mb4;

-- CRIAÇÃO DO BANCO
CREATE DATABASE IF NOT EXISTS yummicious_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE yummicious_db;

-- RESTAURANTES
CREATE TABLE IF NOT EXISTS restaurantes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    horario VARCHAR(100) NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    status ENUM('Aberto', 'Fechado') DEFAULT 'Fechado',
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CLIENTES
CREATE TABLE IF NOT EXISTS clientes (
    id VARCHAR(50) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    saldo DECIMAL(10,2) DEFAULT 0.00,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- PEDIDOS
CREATE TABLE IF NOT EXISTS pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_restaurante INT NULL,
    status ENUM('Pendente', 'Em preparo', 'Rejeitado', 'Finalizado') DEFAULT 'Pendente',
    cliente_id VARCHAR(50) NULL,
    valor_total DECIMAL(10,2) DEFAULT 0.00,
    detalhes TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id_restaurante) REFERENCES restaurantes(id),
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL
);

-- MÉTODOS DE PAGAMENTO
CREATE TABLE IF NOT EXISTS metodos_pagamento (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id VARCHAR(50) NOT NULL,
    tipo ENUM('CREDIT_CARD', 'DEBIT_CARD') NOT NULL,
    ultimos_4_digitos VARCHAR(4) NOT NULL,
    nome_titular VARCHAR(255) NOT NULL,
    validade_mes INT NOT NULL,
    validade_ano INT NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
);

-- TRANSAÇÕES
CREATE TABLE IF NOT EXISTS transacoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pedido_id INT NOT NULL,
    tipo ENUM('PAGAMENTO', 'ESTORNO') NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    status ENUM('PROCESSADO', 'PENDENTE', 'FALHOU') DEFAULT 'PROCESSADO',
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE
);