services:
  db:
    image: mysql:latest
    container_name: ${DB_NAME}
    restart: always
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SECRET_KEY}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./database/db_files:/var/lib/mysql
      - ./database/esquemas:/docker-entrypoint-initdb.d
    networks:
      - delivery_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${BACKEND_NAME}
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - delivery_network

  frontend:
    image: node:jod-alpine
    container_name: ${FRONTEND_NAME}
    restart: always
    working_dir: /app
    environment:
      - TZ=${TZ}
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - delivery_network

networks:
  delivery_network:
    driver: bridge
